### PR TITLE
Fix file quick access

### LINKED ISSUE #162: File Quick Access is not working
When you have a file listed in Quick File Access in the file management tab, export is not working.
When you click the icon to save it on disk, a filename is prompted, then "Data Fetch Denied" error.

In log file:
DEBUG: :0 - JSON API recv: {
    "data": {
        "service": ""
    },
    "msg": "get_data_node"
}
WARNING: :0 - context is empty.

The context sent to the daemon is empty, so no prompt.

When the call to the json api fails, do not continue and ask for a filename.

### PR DESCRIPTION
**Pull request by azubieta**
Fix #162 and #163

### CODE REVIEW

File: src/FilesManagement.cpp [hunk 1]
```diff
@@ -139,12 +139,23 @@ void FilesManagement::setWsClient(WSClient *c)
     {
         loadFilesCacheModel();
     });
+
+    setFileCacheControlsVisible(wsClient->get_fwVersion() >= "v1.2");
```
Comment (raoulh) [inline src/FilesManagement.cpp]: This is not good. String compared like that is likely to fail. The mini version contains also `_mini` at the end.

Please implement wsClient->isFw12() like in MPDevice.

See the implementation in the backend:
https://github.com/mooltipass/moolticute/blob/02a087d2d5b16bb47ead47f35af239f71ef6995a/src/MPDevice.cpp#L400
and 
https://github.com/mooltipass/moolticute/blob/e8b7dd5894f80cff0d1c44689454f877214f4c66/src/MPDevice.h#L211

**Comment by azubieta** [comment]
@raoulh firmware comparison was implemented as you requested please check it.
